# Crear application.properties al mismo nivel que este example, con los mismos campos.
telegram.bot.username=
telegram.bot.token=
integrations.donadores-url=https://entrega-2-lolasimone.onrender.com
integrations.donaciones-url=https://donaciones-xouj.onrender.com
